### ISSUE TITLE
Errors with wordguard

### ISSUE THREAD

**Issue by TymekSL** [RuiPereiraDev/SimpleScore#76]
### Plugin Version

3.12.5

### Server Version

 Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)

### Describe the Bug

        at com.r4g3baby.simplescore.lib.wgwrapper.WorldGuardWrapper.queryFlag(WorldGuardWrapper.java:25) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.scoreboard.worldguard.WorldGuardAPI.getFlag(WorldGuardAPI.kt:33) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.scoreboard.worldguard.WorldGuardAPI.getFlag$default(WorldGuardAPI.kt:31) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.run(ScoreboardTask.kt:47) ~[SimpleScore-3.12.3.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-196]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.internal.platform.WorldGuardPlatform
        ... 14 more
[03:09:34 WARN]: [SimpleScore] Plugin SimpleScore v3.12.3 generated an exception while executing task 59
java.lang.NoClassDefFoundError: com/sk89q/worldguard/internal/platform/WorldGuardPlatform
        at com.r4g3baby.simplescore.lib.wgwrapper.implementation.v7.WorldGuardImplementation.getWorldManager(WorldGuardImplementation.java:85) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.lib.wgwrapper.implementation.v7.WorldGuardImplementation.getApplicableRegions(WorldGuardImplementation.java:89) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.lib.wgwrapper.implementation.v7.WorldGuardImplementation.queryValue(WorldGuardImplementation.java:98) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.lib.wgwrapper.implementation.v7.WorldGuardImplementation.queryFlag(WorldGuardImplementation.java:208) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.lib.wgwrapper.WorldGuardWrapper.queryFlag(WorldGuardWrapper.java:25) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.scoreboard.worldguard.WorldGuardAPI.getFlag(WorldGuardAPI.kt:33) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.scoreboard.worldguard.WorldGuardAPI.getFlag$default(WorldGuardAPI.kt:31) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.run(ScoreboardTask.kt:47) ~[SimpleScore-3.12.3.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-196]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.internal.platform.WorldGuardPlatform
        ... 14 more
[03:09:34 WARN]: [SimpleScore] Plugin SimpleScore v3.12.3 generated an exception while executing task 59
java.lang.NoClassDefFoundError: com/sk89q/worldguard/internal/platform/WorldGuardPlatform
        at com.r4g3baby.simplescore.lib.wgwrapper.implementation.v7.WorldGuardImplementation.getWorldManager(WorldGuardImplementation.java:85) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.lib.wgwrapper.implementation.v7.WorldGuardImplementation.getApplicableRegions(WorldGuardImplementation.java:89) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.lib.wgwrapper.implementation.v7.WorldGuardImplementation.queryValue(WorldGuardImplementation.java:98) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.lib.wgwrapper.implementation.v7.WorldGuardImplementation.queryFlag(WorldGuardImplementation.java:208) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.lib.wgwrapper.WorldGuardWrapper.queryFlag(WorldGuardWrapper.java:25) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.scoreboard.worldguard.WorldGuardAPI.getFlag(WorldGuardAPI.kt:33) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.scoreboard.worldguard.WorldGuardAPI.getFlag$default(WorldGuardAPI.kt:31) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.run(ScoreboardTask.kt:47) ~[SimpleScore-3.12.3.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-196]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.internal.platform.WorldGuardPlatform
        ... 14 more
[03:09:34 WARN]: [SimpleScore] Plugin SimpleScore v3.12.3 generated an exception while executing task 59
java.lang.NoClassDefFoundError: com/sk89q/worldguard/internal/platform/WorldGuardPlatform
        at com.r4g3baby.simplescore.lib.wgwrapper.implementation.v7.WorldGuardImplementation.getWorldManager(WorldGuardImplementation.java:85) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.lib.wgwrapper.implementation.v7.WorldGuardImplementation.getApplicableRegions(WorldGuardImplementation.java:89) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.lib.wgwrapper.implementation.v7.WorldGuardImplementation.queryValue(WorldGuardImplementation.java:98) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.lib.wgwrapper.implementation.v7.WorldGuardImplementation.queryFlag(WorldGuardImplementation.java:208) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.lib.wgwrapper.WorldGuardWrapper.queryFlag(WorldGuardWrapper.java:25) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.scoreboard.worldguard.WorldGuardAPI.getFlag(WorldGuardAPI.kt:33) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.scoreboard.worldguard.WorldGuardAPI.getFlag$default(WorldGuardAPI.kt:31) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.run(ScoreboardTask.kt:47) ~[SimpleScore-3.12.3.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-196]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.internal.platform.WorldGuardPlatform
        ... 14 more
[03:09:34 WARN]: [SimpleScore] Plugin SimpleScore v3.12.3 generated an exception while executing task 59
java.lang.NoClassDefFoundError: com/sk89q/worldguard/internal/platform/WorldGuardPlatform
        at com.r4g3baby.simplescore.lib.wgwrapper.implementation.v7.WorldGuardImplementation.getWorldManager(WorldGuardImplementation.java:85) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.lib.wgwrapper.implementation.v7.WorldGuardImplementation.getApplicableRegions(WorldGuardImplementation.java:89) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.lib.wgwrapper.implementation.v7.WorldGuardImplementation.queryValue(WorldGuardImplementation.java:98) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.lib.wgwrapper.implementation.v7.WorldGuardImplementation.queryFlag(WorldGuardImplementation.java:208) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.lib.wgwrapper.WorldGuardWrapper.queryFlag(WorldGuardWrapper.java:25) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.scoreboard.worldguard.WorldGuardAPI.getFlag(WorldGuardAPI.kt:33) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.scoreboard.worldguard.WorldGuardAPI.getFlag$default(WorldGuardAPI.kt:31) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.run(ScoreboardTask.kt:47) ~[SimpleScore-3.12.3.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-196]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.internal.platform.WorldGuardPlatform
        ... 14 more
[03:09:34 WARN]: [SimpleScore] Plugin SimpleScore v3.12.3 generated an exception while executing task 59
java.lang.NoClassDefFoundError: com/sk89q/worldguard/internal/platform/WorldGuardPlatform
        at com.r4g3baby.simplescore.lib.wgwrapper.implementation.v7.WorldGuardImplementation.getWorldManager(WorldGuardImplementation.java:85) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.lib.wgwrapper.implementation.v7.WorldGuardImplementation.getApplicableRegions(WorldGuardImplementation.java:89) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.lib.wgwrapper.implementation.v7.WorldGuardImplementation.queryValue(WorldGuardImplementation.java:98) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.lib.wgwrapper.implementation.v7.WorldGuardImplementation.queryFlag(WorldGuardImplementation.java:208) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.lib.wgwrapper.WorldGuardWrapper.queryFlag(WorldGuardWrapper.java:25) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.scoreboard.worldguard.WorldGuardAPI.getFlag(WorldGuardAPI.kt:33) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.scoreboard.worldguard.WorldGuardAPI.getFlag$default(WorldGuardAPI.kt:31) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.run(ScoreboardTask.kt:47) ~[SimpleScore-3.12.3.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-196]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.internal.platform.WorldGuardPlatform
        ... 14 more
[03:09:34 WARN]: [SimpleScore] Plugin SimpleScore v3.12.3 generated an exception while executing task 59
java.lang.NoClassDefFoundError: com/sk89q/worldguard/internal/platform/WorldGuardPlatform
        at com.r4g3baby.simplescore.lib.wgwrapper.implementation.v7.WorldGuardImplementation.getWorldManager(WorldGuardImplementation.java:85) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.lib.wgwrapper.implementation.v7.WorldGuardImplementation.getApplicableRegions(WorldGuardImplementation.java:89) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.lib.wgwrapper.implementation.v7.WorldGuardImplementation.queryValue(WorldGuardImplementation.java:98) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.lib.wgwrapper.implementation.v7.WorldGuardImplementation.queryFlag(WorldGuardImplementation.java:208) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.lib.wgwrapper.WorldGuardWrapper.queryFlag(WorldGuardWrapper.java:25) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.scoreboard.worldguard.WorldGuardAPI.getFlag(WorldGuardAPI.kt:33) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.scoreboard.worldguard.WorldGuardAPI.getFlag$default(WorldGuardAPI.kt:31) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.run(ScoreboardTask.kt:47) ~[SimpleScore-3.12.3.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-196]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.internal.platform.WorldGuardPlatform
        ... 14 more
[03:09:34 INFO]: DeadMan712 lost connection: Disconnected
[03:09:34 ERROR]: Could not pass event PlayerQuitEvent to SimpleScore v3.12.3
java.lang.NoClassDefFoundError: com/sk89q/worldguard/internal/platform/WorldGuardPlatform
        at com.r4g3baby.simplescore.lib.wgwrapper.implementation.v7.WorldGuardImplementation.getWorldManager(WorldGuardImplementation.java:85) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.lib.wgwrapper.implementation.v7.WorldGuardImplementation.getApplicableRegions(WorldGuardImplementation.java:89) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.lib.wgwrapper.implementation.v7.WorldGuardImplementation.queryValue(WorldGuardImplementation.java:98) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.lib.wgwrapper.implementation.v7.WorldGuardImplementation.queryFlag(WorldGuardImplementation.java:208) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.lib.wgwrapper.WorldGuardWrapper.queryFlag(WorldGuardWrapper.java:25) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.scoreboard.worldguard.WorldGuardAPI.getFlag(WorldGuardAPI.kt:33) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.scoreboard.ScoreboardManager.needsScoreboard$SimpleScore(ScoreboardManager.kt:78) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.scoreboard.ScoreboardManager.updateScoreboardState$SimpleScore(ScoreboardManager.kt:89) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.scoreboard.ScoreboardManager.updateScoreboardState$SimpleScore$default(ScoreboardManager.kt:86) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.scoreboard.ScoreboardManager$PlayersData.setDisabled(ScoreboardManager.kt:232) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.scoreboard.ScoreboardManager$PlayersData.setDisabled(ScoreboardManager.kt:228) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.scoreboard.ScoreboardManager$PlayersData.setDisabled(ScoreboardManager.kt:227) ~[SimpleScore-3.12.3.jar:?]
        at com.r4g3baby.simplescore.scoreboard.listeners.PacketListener.onPlayerQuit(PacketListener.kt:72) ~[SimpleScore-3.12.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor163.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-196]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:607) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:592) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2178) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2157) ~[?:?]
        at net.minecraft.network.Connection.handleDisconnection(Connection.java:818) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:254) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1586) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.internal.platform.WorldGuardPlatform

**Comment by RuiPereiraDev** [comment]
Hey! Sorry for the delayed response, but I've been away.

[SimpleScore v4](https://modrinth.com/plugin/simplescore/version/4.0.0) should resolve this issue. If not, please feel free to reopen it!
